branch-defaults:
  master:
    environment: null
global:
  application_name: belief-mapper
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.0 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
